### ISSUE TITLE
cannot compile source code due to a 401 Unauthorized

### ISSUE THREAD

**Issue by aturbati** [Ontotext-AD/graphdb-lucene-fts-plugin#9] opened 2022-07-29 09:34 UTC
I've downloaded the project and tried to compile it, but I receive the following error:

Could not resolve dependencies for project com.ontotext.graphdb.plugins:lucene-fts-plugin:jar:3.0-SNAPSHOT: Failed to collect dependencies at com.ontotext.graphdb:graphdb-runtime:jar:10.0.0 -> it.unibz.inf.ontop:ontop-rdf4j-config-sql:jar:4.2.0-RDF4J4-ONTO1: Failed to read artifact descriptor for it.unibz.inf.ontop:ontop-rdf4j-config-sql:jar:4.2.0-RDF4J4-ONTO1: Could not transfer artifact it.unibz.inf.ontop:ontop-rdf4j-config-sql:pom:4.2.0-RDF4J4-ONTO1 from/to owlim-releases (https://maven.ontotext.com/repository/owlim-releases): Authentication failed for https://maven.ontotext.com/repository/owlim-releases/it/unibz/inf/ontop/ontop-rdf4j-config-sql/4.2.0-RDF4J4-ONTO1/ontop-rdf4j-config-sql-4.2.0-RDF4J4-ONTO1.pom 401 Unauthorized

I think that this is because there is at least one dependency that requires to be authenticated to be downloaded and used in the compiling, so only developers that are authenticated to that "site" can now compile the "graphdb-lucene-fts-plugin" (I was able to compile the previous version, the one that worked with GraphDB 9.x)

**Comment by avataar** [comment] 2022-07-29 13:18
We've pushed a fix. Please pull the master and try again.

**Comment by aturbati** [comment] 2022-07-29 13:34
I've downloaded the latest version (I've checked and I see in the pom the "<exclusions>" in the "<artifactId>graphdb-runtime</artifactId>" ) but now I get a similar error:

Could not resolve dependencies for project com.ontotext.graphdb.plugins:lucene-fts-plugin:jar:3.0-SNAPSHOT: Failed to collect dependencies at com.ontotext.graphdb:graphdb-tests-base:jar:10.0.0 -> it.unibz.inf.ontop:ontop-rdf4j-config-sql:jar:4.2.0-RDF4J4-ONTO1: Failed to read artifact descriptor for it.unibz.inf.ontop:ontop-rdf4j-config-sql:jar:4.2.0-RDF4J4-ONTO1: Could not transfer artifact it.unibz.inf.ontop:ontop-rdf4j-config-sql:pom:4.2.0-RDF4J4-ONTO1 from/to owlim-releases (https://maven.ontotext.com/repository/owlim-releases): Authentication failed for https://maven.ontotext.com/repository/owlim-releases/it/unibz/inf/ontop/ontop-rdf4j-config-sql/4.2.0-RDF4J4-ONTO1/ontop-rdf4j-config-sql-4.2.0-RDF4J4-ONTO1.pom 401 Unauthorized

the difference between this one and the previous one is that i the previous one there was "com.ontotext.graphdb:graphdb-runtime:jar:10.0.0" while now there is "com.ontotext.graphdb:graphdb-tests-base:jar:10.0.0". I think that is because you excluded just in the <artifactId>graphdb-runtime</artifactId>

**Comment by avataar** [comment] 2022-07-29 13:42
Sorry for that. Added now to the other dependency as well. The tests may print a long stack trace that begins with:
```
[main] ERROR o.e.r.r.config.RepositoryRegistry - Failed to instantiate service
java.lang.NoClassDefFoundError: it/unibz/inf/ontop/rdf4j/repository/OntopRepositoryFactory
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
```

That is caused by the exclusion of the dependency and doesn't interfere with running the tests.

**Comment by aturbati** [comment] 2022-07-29 14:34
Now I'm able to compile, thank you (during the process I got many times the "com.ontotext.plugin.lucene - The Lucene FTS plugin has been deprecated in favour of new functionality in the Connectors." message but I think this is normal)

**Comment by avataar** [comment] 2022-07-29 14:57
Yes, that message is normal.

**Closed as completed by avataar** 2022-07-29 14:57 UTC
